// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mAS_TOeoGm8rOXBqZ8uggrulJODRSuw',
    appId: '1:146559621172:web:99f03946158ff2a17c9261',
    messagingSenderId: '146559621172',
    projectId: 'incluyeme-app',
    authDomain: 'incluyeme-app.firebaseapp.com',
    storageBucket: 'incluyeme-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQZBKfwhQdgBRPiYEwdxccVDkWdBxLlg',
    appId: '1:146559621172:android:e3eed4c785228ba17c9261',
    messagingSenderId: '146559621172',
    projectId: 'incluyeme-app',
    storageBucket: 'incluyeme-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBq13Fl4cKYacMWfrtjgoAs-gt1CzxnRw',
    appId: '1:146559621172:ios:503c0d51993fbc7a7c9261',
    messagingSenderId: '146559621172',
    projectId: 'incluyeme-app',
    storageBucket: 'incluyeme-app.firebasestorage.app',
    iosClientId: '146559621172-in1qlgubqnulnc8r90dmabul6lemqtg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.incluyeme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBq13Fl4cKYacMWfrtjgoAs-gt1CzxnRw',
    appId: '1:146559621172:ios:a4a0dd269ad5e4d27c9261',
    messagingSenderId: '146559621172',
    projectId: 'incluyeme-app',
    storageBucket: 'incluyeme-app.firebasestorage.app',
    iosClientId: '146559621172-2dje71eku5qr85gbu9qjrca9b3cmancs.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mAS_TOeoGm8rOXBqZ8uggrulJODRSuw',
    appId: '1:146559621172:web:d95e0426af981f527c9261',
    messagingSenderId: '146559621172',
    projectId: 'incluyeme-app',
    authDomain: 'incluyeme-app.firebaseapp.com',
    storageBucket: 'incluyeme-app.firebasestorage.app',
  );
}
